[2022-09-09 08:41:15,897] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: trip_etl.ssh_task 2022-09-09T08:41:15.009346+00:00 [queued]>
[2022-09-09 08:41:15,905] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: trip_etl.ssh_task 2022-09-09T08:41:15.009346+00:00 [queued]>
[2022-09-09 08:41:15,905] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2022-09-09 08:41:15,906] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2022-09-09 08:41:15,906] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2022-09-09 08:41:15,916] {taskinstance.py:1089} INFO - Executing <Task(SSHOperator): ssh_task> on 2022-09-09T08:41:15.009346+00:00
[2022-09-09 08:41:15,925] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trip_etl', 'ssh_task', '2022-09-09T08:41:15.009346+00:00', '--job-id', '80', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse test.py', '--cfg-path', '/tmp/tmplhfex9y4', '--error-file', '/tmp/tmp2dm7uhvy']
[2022-09-09 08:41:15,919] {standard_task_runner.py:52} INFO - Started process 79 to run task
[2022-09-09 08:41:15,926] {standard_task_runner.py:77} INFO - Job 80: Subtask ssh_task
[2022-09-09 08:41:15,967] {logging_mixin.py:104} INFO - Running <TaskInstance: trip_etl.ssh_task 2022-09-09T08:41:15.009346+00:00 [running]> on host 3f125d5f6fbd
[2022-09-09 08:41:15,995] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trip_etl
AIRFLOW_CTX_TASK_ID=ssh_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-09T08:41:15.009346+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-09T08:41:15.009346+00:00
[2022-09-09 08:41:15,996] {ssh.py:91} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2022-09-09 08:41:16,002] {base.py:78} INFO - Using connection to: id: nfrssh. Host: 192.168.16.1, Port: 22, Schema: , Login: nfrs, Password: XXXXXXXX, extra: None
[2022-09-09 08:41:16,002] {ssh.py:204} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2022-09-09 08:41:16,003] {ssh.py:210} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2022-09-09 08:41:16,025] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_8.1)
[2022-09-09 08:41:16,121] {transport.py:1819} INFO - Authentication (password) successful!
[2022-09-09 08:41:16,122] {ssh.py:110} INFO - Running command: cd Documents && python trip_etl.py
[2022-09-09 08:41:16,316] {ssh.py:146} WARNING - Traceback (most recent call last):
  File "C:\Users\nfrs\Documents\trip_etl.py", line 7, in <module>
[2022-09-09 08:41:16,318] {ssh.py:146} WARNING -     import requests
[2022-09-09 08:41:16,318] {ssh.py:146} WARNING - ModuleNotFoundError: No module named 'requests'
[2022-09-09 08:41:16,332] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/ssh/operators/ssh.py", line 169, in execute
    raise AirflowException(f"error running cmd: {self.command}, error: {error_msg}")
airflow.exceptions.AirflowException: error running cmd: cd Documents && python trip_etl.py, error: Traceback (most recent call last):
  File "C:\Users\nfrs\Documents\trip_etl.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/ssh/operators/ssh.py", line 172, in execute
    raise AirflowException(f"SSH operator error: {str(e)}")
airflow.exceptions.AirflowException: SSH operator error: error running cmd: cd Documents && python trip_etl.py, error: Traceback (most recent call last):
  File "C:\Users\nfrs\Documents\trip_etl.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

[2022-09-09 08:41:16,333] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=trip_etl, task_id=ssh_task, execution_date=20220909T084115, start_date=20220909T084115, end_date=20220909T084116
[2022-09-09 08:41:16,382] {local_task_job.py:146} INFO - Task exited with return code 1
